# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161030_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
