# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_client_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='client',
            name='service',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
    ]
