# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20161121_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='ip',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='service',
            field=models.CharField(choices=[('trainer', 'trainer'), ('dietitian', 'dietitian'), ('both', 'both'), ('none', 'none')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
