# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=30)),
                ('lastname', models.CharField(default=None, max_length=30)),
                ('gender', models.CharField(default=None, max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('city', models.CharField(default=None, max_length=200)),
                ('state', models.CharField(default=None, max_length=200)),
                ('ip', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='service',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='certification',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='basicinfo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.BasicProfile'),
        ),
    ]
