# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20161124_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicprofile',
            name='ip',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
