# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20161127_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicprofile',
            name='ip',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
