# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20161127_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='basicinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.BasicProfile'),
        ),
    ]
