# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 04:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_auto_20161127_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietitianProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='trainer', max_length=200)),
                ('basicinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.BasicProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(default=None, max_length=30)),
                ('service', models.CharField(default='trainer', max_length=200)),
                ('basicinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.BasicProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='certification',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='service',
            field=models.CharField(default='client', max_length=200),
        ),
    ]
