# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20161130_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicprofile',
            old_name='member_type',
            new_name='membertype',
        ),
    ]
