# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20161130_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicprofile',
            name='isClient',
        ),
        migrations.RemoveField(
            model_name='basicprofile',
            name='isDietitian',
        ),
        migrations.RemoveField(
            model_name='basicprofile',
            name='isTrainer',
        ),
        migrations.AddField(
            model_name='basicprofile',
            name='membertype',
            field=models.CharField(choices=[('trainer', 'trainer'), ('dietitian', 'dietitian'), ('client', 'client')], default='client', max_length=30),
        ),
    ]
