# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20161202_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='trainer_pending',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='trainerpending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainerpending', to='api.TrainerProfile'),
        ),
    ]
