# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20161202_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default=None, max_length=100),
        ),
    ]
