# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20161209_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=100),
        ),
    ]
