# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_ex_excat_exercise_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excat',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='api.Ex'),
        ),
    ]
