# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20161211_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excat',
            name='exercise',
        ),
        migrations.AddField(
            model_name='ex',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='api.ExCat'),
        ),
        migrations.AddField(
            model_name='excat',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
