# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20161211_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ex',
            old_name='exercise',
            new_name='category',
        ),
    ]
