# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20161211_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ex',
            name='category',
        ),
        migrations.DeleteModel(
            name='Ex',
        ),
        migrations.DeleteModel(
            name='ExCat',
        ),
    ]
