# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20161211_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ex',
            new_name='ExList',
        ),
    ]
