# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20161211_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exlist',
            old_name='category',
            new_name='ecategory',
        ),
    ]
