# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_allexercises'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllExercises',
            new_name='Exercise',
        ),
    ]
