# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20161211_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercise',
            new_name='AllExercise',
        ),
    ]
