# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20161211_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllExercise',
            new_name='Exercise',
        ),
    ]
