# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20161211_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecategory',
            old_name='name',
            new_name='catname',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='name',
            new_name='exname',
        ),
    ]
