# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20161211_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='ecategory',
        ),
        migrations.DeleteModel(
            name='ECategory',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
