# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_ecategory_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='ecategory',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exname',
        ),
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.DeleteModel(
            name='ECategory',
        ),
    ]
