# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20161211_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='api.Category'),
        ),
    ]
