# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_exercise_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('suggestreps', models.PositiveIntegerField(default=0)),
                ('suggestsets', models.PositiveIntegerField(default=0)),
                ('actualreps', models.PositiveIntegerField(default=0)),
                ('actualsets', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='clientexercise',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='api.ClientWorkout'),
        ),
    ]
