# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20161212_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientexercise',
            name='actualreps',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clientexercise',
            name='actualsets',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clientexercise',
            name='suggestreps',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clientexercise',
            name='suggestsets',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
